import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from './pages/Header'
import Footer from './pages/Footer'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container flex flex-col min-h-[100vh] mx-auto">
          <Header />
          <main className="flex flex-1">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
